// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDx2nyxyrX5h6iHe0KRZU1ih-6hANdF1Eo',
    appId: '1:1055101780037:web:7d9ac6bd1d157412b6e32c',
    messagingSenderId: '1055101780037',
    projectId: 'dreamnotes-1c7e1',
    authDomain: 'dreamnotes-1c7e1.firebaseapp.com',
    storageBucket: 'dreamnotes-1c7e1.firebasestorage.app',
    measurementId: 'G-97TZXFMG6Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7VQWLd5ce7dsjrvIVhc6SRCuAlKQMa1s',
    appId: '1:1055101780037:android:7aceb28a644c9890b6e32c',
    messagingSenderId: '1055101780037',
    projectId: 'dreamnotes-1c7e1',
    storageBucket: 'dreamnotes-1c7e1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4E8jJurJA8YnDGD2AAFu4ZOywVcWEXUg',
    appId: '1:1055101780037:ios:c31b658c3a7087b0b6e32c',
    messagingSenderId: '1055101780037',
    projectId: 'dreamnotes-1c7e1',
    storageBucket: 'dreamnotes-1c7e1.firebasestorage.app',
    iosBundleId: 'com.example.dreamNotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4E8jJurJA8YnDGD2AAFu4ZOywVcWEXUg',
    appId: '1:1055101780037:ios:c31b658c3a7087b0b6e32c',
    messagingSenderId: '1055101780037',
    projectId: 'dreamnotes-1c7e1',
    storageBucket: 'dreamnotes-1c7e1.firebasestorage.app',
    iosBundleId: 'com.example.dreamNotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDx2nyxyrX5h6iHe0KRZU1ih-6hANdF1Eo',
    appId: '1:1055101780037:web:3cbfdf340732a130b6e32c',
    messagingSenderId: '1055101780037',
    projectId: 'dreamnotes-1c7e1',
    authDomain: 'dreamnotes-1c7e1.firebaseapp.com',
    storageBucket: 'dreamnotes-1c7e1.firebasestorage.app',
    measurementId: 'G-FNM15JNC16',
  );
}
